### ISSUE TITLE
Using a secret-id starting with 't' fails

### ISSUE THREAD

**Issue by brett-anderson** [seek-oss/aws-sm-buildkite-plugin#16]
```
steps:
  - commands: 'echo \$MY_SECRET'
    plugins:
      - seek-oss/aws-sm#v2.1.0:
          json-to-env:
            - secret-id: "test-variable-secrets"
              json-key: ".Variables"
```
The secret-id in this example will fail, as the plugin parses the secret-id as "est-variable-secrets"

<img width="513" alt="Screen Shot 2020-06-25 at 1 06 13 PM" src="https://user-images.githubusercontent.com/3645267/85774644-aaa59b00-b6e4-11ea-8516-147d05db07c1.png">

We got around this by renaming our secret-id and it worked.
