### ISSUE TITLE
extra blank lines in buildkite log output

### ISSUE THREAD

**Issue by andrewhsu** [seek-oss/aws-sm-buildkite-plugin#30]
using the plugin to retrieve secrets with json key:
```yaml
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - json-key: .
              secret-id: prod/AppBeta/Mysql
            - json-key: .
              secret-id: prod/AppBeta/Redpanda
```
the buildkite log has 2 extra blank lines per secret:
```
  | 2024-07-02 00:46:37 CDT | 🔑 Reading secrets from AWS SM
  | 2024-07-02 00:46:37 CDT | Reading all environment variables from prod/AppBeta/Mysql in AWS SM
  | 2024-07-02 00:46:37 CDT |  
  | 2024-07-02 00:46:37 CDT |  
  | 2024-07-02 00:46:37 CDT | Setting environment variable MYSQL_DSN
  | 2024-07-02 00:46:37 CDT | Reading all environment variables from prod/AppBeta/Redpanda in AWS SM
  | 2024-07-02 00:46:37 CDT |  
  | 2024-07-02 00:46:38 CDT |  
  | 2024-07-02 00:46:38 CDT | Setting environment variable REDPANDA_USER
  | 2024-07-02 00:46:38 CDT | Setting environment variable REDPANDA_PASSWORD
```
removing the blank lines would make it easier for human eyes to associate aws sm secret name with env var name
