### ISSUE TITLE
Support convention based secrets

### ISSUE THREAD

**Issue by zsims** [seek-oss/aws-sm-buildkite-plugin#6]
It would be nice to load secrets based on the existence of named environment variables, e.g.

```
env:
  EXAMPLE_SECRET_ID: 'my secret id'

steps:
  - command: echo $$EXAMPLE
    plugins:
      seek-oss/aws-sm#not-released-yet
```
